service: n8n
image: edoardodep/n8n

servers:
  - 188.245.178.80

proxy:
  ssl: true
  hosts:
    - n8n.blanchefoodtruck.it
  app_port: 5678        # make sure this matches the port n8n listens on
  healthcheck:
    path: /healthz       # appropriate for n8n
    interval: 10        # seconds between checks
    timeout: 5          # how long to wait per check


registry:
  username: edoardodep
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - n8n_data:/home/node/.n8n

builder:
  arch: arm64

ssh:
  user: root