service: n8n
image: n8nio/n8n:latest

ssh:
  user: ubuntu

servers:
  web:
    hosts:
      - 188.245.178.80

env:
  clear:
    N8N_HOST: n8n.blanchefoodtruck.it
    N8N_PROTOCOL: https
    N8N_PORT: "443"
    WEBHOOK_URL: https://n8n.blanchefoodtruck.it/
    TZ: Europe/Rome
  secret:
    - N8N_BASIC_AUTH_ACTIVE
    - N8N_BASIC_AUTH_USER
    - N8N_BASIC_AUTH_PASSWORD
    - N8N_ENCRYPTION_KEY

volumes:
  - "/home/ubuntu/.n8n:/home/node/.n8n"

proxy:
  host: n8n.blanchefoodtruck.it
  ssl: true
  app_port: 5678
  forward_headers: true
  healthcheck:
    path: /healthz
    interval: 2
    timeout: 120
