service: n8n
image: edoardodep/n8n

servers:
  - 188.245.178.80

proxy:
  ssl: true
  hosts:
    - n8n.blanchefoodtruck.it

registry:
  username: edoardodep
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - n8n_data:/home/node/.n8n

builder:
  arch: arm64

ssh:
  user: root

healthcheck:
  path: /healthz
  port: "5678"
  interval: 10s
  max_attempts: 20
  log_lines: 200