service: n8n
image: edoardodep/n8n

servers:
  - 188.245.178.80

proxy:
  ssl: true
  hosts:
    - n8n.edodep.com
  app_port: 5678
  healthcheck:
    path: /healthz
    interval: 10
    timeout: 5


registry:
  username: edoardodep
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - n8n_data:/home/node/.n8n

builder:
  arch: arm64

ssh:
  user: root