service: n8n
image: n8nio/n8n

servers:
  - 188.245.178.80

proxy:
  ssl: true
  hosts:
    - n8n.blanchefoodtruck.it

registry:
  username: edoardodep
  password:
    - KAMAL_REGISTRY_PASSWORD

volumes:
  - "/var/lib/n8n:/home/node/.n8n"

builder:
  arch: arm64

ssh:
  user: root